### PR TITLE
Add french HH.exe

### PR DESCRIPTION
**Pull request by frack113**
atomic-red-team issue [1714] (https://github.com/redcanaryco/atomic-red-team/issues/1714)
Add french version of hh.exe
Capture

### CODE REVIEW

**Comment by mgraeber-rc** [comment]
Thank you for reporting this and submitting a PR, @frack113! Good catch. This silly American wouldn't have considered that the product name would be anything but English. Haha. Ideally, I'd love to fix this issue in a language-agnostic way. Can you do me a favor? What does the following return for you? `(Get-Item C:\Windows\hh.exe).VersionInfo.OriginalFilename`

Does it return `HH.exe.mui`? If so, I think performing the check based on OriginalFilename would be a more durable fix that wouldn't require maintaining checks for each language. Let me know. Thanks!

**Comment by frack113** [comment]
Yes 👍 
image

**Comment by mgraeber-rc** [comment]
Thanks for checking! Would you like to revise the PR to capture this update? I also don't mind making the change.

**Comment by frack113** [comment]
Ok make and test on windows 10 x64 21h2 Franch

**Review by mgraeber-rc — APPROVED** [review]
This looks great. Thanks so much for making the change and submitting the PR!

**Pull request merged**
